#!/bin/bash

model=$1
example_dir=$2
output_dir=$3
timeout_time=$4 #sec
max_length=$5
index=$6

exec_test() {
    (
        bash -c "/usr/bin/time -f '%U'\
            timeout ${timeout_time} \
            $(dirname $0)/gen_program.sh ${model} ${example_dir}/$1-example.json ${max_length} $2 $3" \
            2>&1 > /dev/null
        result=$?
        if [ $result -eq 124 ]
        then
            echo ${timeout_time}
        elif [ $result -eq 1 ]
        then
            echo "not found"
        elif [ $result -ne 0 ]
        then
            echo "error"
        fi
    ) | tail -1
}

echo "Index_Of_Program,Time_NONE,Time_DFS,Time_DFS_WREMOVAL" >> ~/comma_separated.txt

while [ -e "${example_dir}/${index}-example.json" ] && [ $index -lt 40 ]
do
    echo "${index}: Start"
    time_dfs_with_removal=$(exec_test $index dfs wremoval)
    echo "${index}: DFS with removal ${time_dfs_with_removal}"
    time_dfs=$(exec_test $index dfs none)
    echo "${index}: DFS ${time_dfs}"
    #time_sae=$(exec_test $index)
    #echo "${index}: SAE ${time_sae}"
    time_none=$(exec_test $index none)
    echo "${index}: None ${time_none}"
    echo ${index},${time_none},${time_dfs},${time_dfs_with_removal} >> ${output_dir}/comma_separated.txt
    ((index++)) 
done
    echo "${index}: Finish"

